#!/bin/bash
COLOR_REST='\e[0m'
COLOR_GREEN='\e[0;32m';
COLOR_RED='\e[0;31m';
COLOR_GRAY='\e[90m';
GreenOK=`echo -en "${COLOR_GREEN}--> OK${COLOR_REST}"`
RedFAIL=`echo -en "${COLOR_RED}--> Fail${COLOR_REST}"`
#https://misc.flogisoft.com/bash/tip_colors_and_formatting
# ==== OS version ====
echo " ==== OS version ==== " 
uname -a 
echo " ==== Disk information ==== " 
echo " == lsblk" 
lsblk 
echo " == df -Th" 
df -Th 
echo " == cat /proc/mdstat" 
cat /proc/mdstat  

# SSHD check
SSHDCip=$(grep "Ciphers" /etc/ssh/sshd_config) 
SSHDMac=$(grep "MACs" /etc/ssh/sshd_config) 
SSHDC=$(grep "Ciphers aes128-ctr,aes192-ctr,aes256-ctr" /etc/ssh/sshd_config|wc -l) 
SSHDM=$(grep "MACs hmac-sha2-256,hmac-sha2-512" /etc/ssh/sshd_config|wc -l) 
echo " ==== SSHD Ciphers CHECK ==== " 
if [ $SSHDC == 1 ];then
echo "SSHD Ciphers Check " $GreenOK
echo $SSHDCip 
else
echo "SSHD Ciphers Check " $RedFAIL "you must do"

echo -en "${COLOR_GRAY}echo \"Ciphers aes128-ctr,aes192-ctr,aes256-ctr\" >> /etc/ssh/sshd_config${COLOR_REST}" 
echo ''
fi
if [ $SSHDM == 1 ];then
echo "SSHD Macs Check" $GreenOK
echo $SSHDMac 
else
echo "SSHD Macs Check" $RedFAIL "you must do" 
echo -en "${COLOR_GRAY}echo \"MACs hmac-sha2-256,hmac-sha2-512\" >> /etc/ssh/sshd_config${COLOR_REST}" 
fi

# CR10S check
echo ""
echo " ==== CR10S check ==== " 
PCSCD=$(grep "PCSCD_OPTIONS=--critical" /etc/rc.d/init.d/pcscd)
PCSCD2=$(grep "PCSCD_OPTIONS=--critical" /etc/rc.d/init.d/pcscd|wc -l)
if [ $PCSCD2 == 1 ] ;then
echo "Card Reader" $GreenOK 
echo $PCSCD 
else
echo "Card Reader" $RedFAIL 
echo $PCSCD 
echo "you must do" 
echo -en "${COLOR_GRAY}sed -i 's/PCSCD_OPTIONS=/PCSCD_OPTIONS=--critical/g' /etc/rc.d/init.d/pcscd ${COLOR_REST}" 
fi

echo " ==== check finish ==== " 

